import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientLayout>
          {children}
        </ClientLayout>
        <footer className="footer footer-horizontal text-base-content text-gray-600 p-10 myfooter">
        <div className="flex flex-col"></div>
        <aside>
          <img src="https://cdn.discordapp.com/attachments/1385609400923717773/1401160949565620326/Screenshot_2025-08-02_113134.png?ex=688f4452&is=688df2d2&hm=056bc631a42865537e7e7f02dbd541ca2ab2d6f0c74c6499c0c9e2dff882988b&" alt=".." className="w-[300px] h-auto"/>
          <div className="flex flex-row">
            <div><img src="https://cdn.discordapp.com/attachments/1385609400923717773/1401164121134862387/Screenshot_2025-08-02_132529.png?ex=688f4746&is=688df5c6&hm=9ed024ec10f8477b258beb59e23f4a8c4ea2ec44e841f1014daff093a08908ae&" alt=".." className="w-[20px] h-auto"/></div>
            <div><p>Enquiry@VibeStrings.com</p></div></div>
          <div className="flex flex-row">
            <div><img src="https://cdn.discordapp.com/attachments/1385609400923717773/1401164121357156462/Screenshot_2025-08-02_132539.png?ex=688f4746&is=688df5c6&hm=3f8a4756a3c1687ec9ffdfa85bbb04b3b106fe8c64fb7eec02bc8ea2e02c6a01&" alt=".." className="w-[20px] h-auto"/></div>
            <div><p>San Francisco</p></div>
            </div>
        </aside>
        <nav>
          <h1 className="text-xl font-semibold footer-title text-black">Pages</h1>
          <a className="link link-hover">Store</a>
          <a className="link link-hover">Collections</a>
          <a className="link link-hover">Support</a>
        </nav>
        <nav>
          <h3 className="text-xl font-semibold footer-title text-black">Product</h3>
          <a className="link link-hover">Terms</a>
          <a className="link link-hover">Privacy policy</a>
          <a className="link link-hover">Copy right</a>
        </nav>
        <nav>
          <h1 className="text-xl font-semibold footer-title text-black">Follow us</h1>
          <div className="grid grid-flow-col gap-4">
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current">
                <path
                  d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
              </svg>
            </a>
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current">
                <path
                  d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
              </svg>
            </a>
            <a>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="fill-current">
                <path
                  d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
              </svg>
            </a>
          </div>
        </nav>
        
      </footer>
      <footer className="footer footer-center  text-base-content text-gray-600 p-10 myfooter">
        <div className="container mx-auto px-4 text-center sm:px-6 lg:px-8">
            <p className="text-center">© 2022 Copyright.VibeStrings</p>
        </div>
      </footer>
      </body>
    </html>
  );
}
